// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"hmall/application/order/rpc/internal/logic"
	"hmall/application/order/rpc/internal/svc"
	"hmall/application/order/rpc/pb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) FindOrderById(ctx context.Context, in *pb.FindOrderByIdReq) (*pb.FindOrderByIdResp, error) {
	l := logic.NewFindOrderByIdLogic(ctx, s.svcCtx)
	return l.FindOrderById(in)
}
