// Code generated by goctl. DO NOT EDIT.
package types

type Resp struct {
}

type QueryCartResp struct {
	Items []ItemDTO `json:"items"`
}

type ItemDTO struct {
	CreateTime string `json:"createTime"`
	Id         int    `json:"id"`
	Image      string `json:"image"`
	ItemId     int    `json:"itemId"`
	Name       string `json:"name"`
	NewPrice   int    `json:"newPrice"`
	Num        int    `json:"num"`
	Price      int    `json:"price"`
	Spec       string `json:"spec"`
	Status     int    `json:"status"`
	Stock      int    `json:"stock"`
}

type AddCartReq struct {
	Image   string `json:"image"`
	ItemId int    `json:"itemId"`
	Name    string `json:"name"`
	Spec    string `json:"spec"`
	Price   int    `json:"price"`
	Num int `json:"num"`
}

type UpdateCartReq struct {
	ItemDTO
}

type DelCartItemsReq struct {
	Ids []string `json:"ids"`
}

type DelCartItemReq struct {
	Id int `path:"id"`
}
