// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.3
// source: user.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserClient interface {
	DecutMoney(ctx context.Context, in *DecutMoneyReq, opts ...grpc.CallOption) (*DecutMoneyResp, error)
	DecutMoneyRollBack(ctx context.Context, in *DecutMoneyReq, opts ...grpc.CallOption) (*DecutMoneyResp, error)
}

type userClient struct {
	cc grpc.ClientConnInterface
}

func NewUserClient(cc grpc.ClientConnInterface) UserClient {
	return &userClient{cc}
}

func (c *userClient) DecutMoney(ctx context.Context, in *DecutMoneyReq, opts ...grpc.CallOption) (*DecutMoneyResp, error) {
	out := new(DecutMoneyResp)
	err := c.cc.Invoke(ctx, "/service.User/DecutMoney", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) DecutMoneyRollBack(ctx context.Context, in *DecutMoneyReq, opts ...grpc.CallOption) (*DecutMoneyResp, error) {
	out := new(DecutMoneyResp)
	err := c.cc.Invoke(ctx, "/service.User/DecutMoneyRollBack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
// All implementations must embed UnimplementedUserServer
// for forward compatibility
type UserServer interface {
	DecutMoney(context.Context, *DecutMoneyReq) (*DecutMoneyResp, error)
	DecutMoneyRollBack(context.Context, *DecutMoneyReq) (*DecutMoneyResp, error)
	mustEmbedUnimplementedUserServer()
}

// UnimplementedUserServer must be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (UnimplementedUserServer) DecutMoney(context.Context, *DecutMoneyReq) (*DecutMoneyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecutMoney not implemented")
}
func (UnimplementedUserServer) DecutMoneyRollBack(context.Context, *DecutMoneyReq) (*DecutMoneyResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecutMoneyRollBack not implemented")
}
func (UnimplementedUserServer) mustEmbedUnimplementedUserServer() {}

// UnsafeUserServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServer will
// result in compilation errors.
type UnsafeUserServer interface {
	mustEmbedUnimplementedUserServer()
}

func RegisterUserServer(s grpc.ServiceRegistrar, srv UserServer) {
	s.RegisterService(&User_ServiceDesc, srv)
}

func _User_DecutMoney_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecutMoneyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DecutMoney(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.User/DecutMoney",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DecutMoney(ctx, req.(*DecutMoneyReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_DecutMoneyRollBack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecutMoneyReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).DecutMoneyRollBack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.User/DecutMoneyRollBack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).DecutMoneyRollBack(ctx, req.(*DecutMoneyReq))
	}
	return interceptor(ctx, in, info, handler)
}

// User_ServiceDesc is the grpc.ServiceDesc for User service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var User_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DecutMoney",
			Handler:    _User_DecutMoney_Handler,
		},
		{
			MethodName: "DecutMoneyRollBack",
			Handler:    _User_DecutMoneyRollBack_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}
