// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"hmall/application/item/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodDelete,
				Path:    "/:id",
				Handler: DelItemByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: FindItemByIdHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/stock/deduct",
				Handler: DeductItemsHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/status/:id/:status",
				Handler: UpdateItemStatusHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/page",
				Handler: QueryItemPageHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/",
				Handler: UpdateItemHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: AdditemHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/",
				Handler: FindItemsByIdHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/items"),
	)
}
