// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Password   string `json:"password"`
	RememberMe bool   `json:"rememberMe"`
	UserName   string `json:"userName"`
}

type LoginResp struct {
	Balance  int    `json:"balance"`
	Token    string `json:"token"`
	UserId   int    `json:"userId"`
	UserName string `json:"userName"`
}

type DeductMoneyReq struct {
	Amount string `json:"amount"`
	Pw     string `json:"pw"`
}
