// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: pay.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdatePayOrderReq_PayTypeEnum int32

const (
	UpdatePayOrderReq__                 UpdatePayOrderReq_PayTypeEnum = 0
	UpdatePayOrderReq_H5                UpdatePayOrderReq_PayTypeEnum = 1
	UpdatePayOrderReq_Applet            UpdatePayOrderReq_PayTypeEnum = 2
	UpdatePayOrderReq_Multitude_Account UpdatePayOrderReq_PayTypeEnum = 3
	UpdatePayOrderReq_Scan_Code         UpdatePayOrderReq_PayTypeEnum = 4
	UpdatePayOrderReq_Balance           UpdatePayOrderReq_PayTypeEnum = 5
)

// Enum value maps for UpdatePayOrderReq_PayTypeEnum.
var (
	UpdatePayOrderReq_PayTypeEnum_name = map[int32]string{
		0: "_",
		1: "H5",
		2: "Applet",
		3: "Multitude_Account",
		4: "Scan_Code",
		5: "Balance",
	}
	UpdatePayOrderReq_PayTypeEnum_value = map[string]int32{
		"_":                 0,
		"H5":                1,
		"Applet":            2,
		"Multitude_Account": 3,
		"Scan_Code":         4,
		"Balance":           5,
	}
)

func (x UpdatePayOrderReq_PayTypeEnum) Enum() *UpdatePayOrderReq_PayTypeEnum {
	p := new(UpdatePayOrderReq_PayTypeEnum)
	*p = x
	return p
}

func (x UpdatePayOrderReq_PayTypeEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdatePayOrderReq_PayTypeEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_pay_proto_enumTypes[0].Descriptor()
}

func (UpdatePayOrderReq_PayTypeEnum) Type() protoreflect.EnumType {
	return &file_pay_proto_enumTypes[0]
}

func (x UpdatePayOrderReq_PayTypeEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdatePayOrderReq_PayTypeEnum.Descriptor instead.
func (UpdatePayOrderReq_PayTypeEnum) EnumDescriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{0, 0}
}

type UpdatePayOrderReq_PayStatus int32

const (
	UpdatePayOrderReq_Wait_Commit UpdatePayOrderReq_PayStatus = 0
	UpdatePayOrderReq_Wait_Pay    UpdatePayOrderReq_PayStatus = 1
	UpdatePayOrderReq_PayTimeOut  UpdatePayOrderReq_PayStatus = 2
	UpdatePayOrderReq_Pay_Success UpdatePayOrderReq_PayStatus = 3
)

// Enum value maps for UpdatePayOrderReq_PayStatus.
var (
	UpdatePayOrderReq_PayStatus_name = map[int32]string{
		0: "Wait_Commit",
		1: "Wait_Pay",
		2: "PayTimeOut",
		3: "Pay_Success",
	}
	UpdatePayOrderReq_PayStatus_value = map[string]int32{
		"Wait_Commit": 0,
		"Wait_Pay":    1,
		"PayTimeOut":  2,
		"Pay_Success": 3,
	}
)

func (x UpdatePayOrderReq_PayStatus) Enum() *UpdatePayOrderReq_PayStatus {
	p := new(UpdatePayOrderReq_PayStatus)
	*p = x
	return p
}

func (x UpdatePayOrderReq_PayStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdatePayOrderReq_PayStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_pay_proto_enumTypes[1].Descriptor()
}

func (UpdatePayOrderReq_PayStatus) Type() protoreflect.EnumType {
	return &file_pay_proto_enumTypes[1]
}

func (x UpdatePayOrderReq_PayStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdatePayOrderReq_PayStatus.Descriptor instead.
func (UpdatePayOrderReq_PayStatus) EnumDescriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{0, 1}
}

type UpdatePayOrderReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PayType UpdatePayOrderReq_PayTypeEnum `protobuf:"varint,1,opt,name=PayType,proto3,enum=service.UpdatePayOrderReq_PayTypeEnum" json:"PayType,omitempty"`
	Status  UpdatePayOrderReq_PayStatus   `protobuf:"varint,2,opt,name=Status,proto3,enum=service.UpdatePayOrderReq_PayStatus" json:"Status,omitempty"`
	PayTime string                        `protobuf:"bytes,4,opt,name=PayTime,proto3" json:"PayTime,omitempty"`
}

func (x *UpdatePayOrderReq) Reset() {
	*x = UpdatePayOrderReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePayOrderReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePayOrderReq) ProtoMessage() {}

func (x *UpdatePayOrderReq) ProtoReflect() protoreflect.Message {
	mi := &file_pay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePayOrderReq.ProtoReflect.Descriptor instead.
func (*UpdatePayOrderReq) Descriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{0}
}

func (x *UpdatePayOrderReq) GetPayType() UpdatePayOrderReq_PayTypeEnum {
	if x != nil {
		return x.PayType
	}
	return UpdatePayOrderReq__
}

func (x *UpdatePayOrderReq) GetStatus() UpdatePayOrderReq_PayStatus {
	if x != nil {
		return x.Status
	}
	return UpdatePayOrderReq_Wait_Commit
}

func (x *UpdatePayOrderReq) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

type UpdatePayOrderResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
}

func (x *UpdatePayOrderResp) Reset() {
	*x = UpdatePayOrderResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePayOrderResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePayOrderResp) ProtoMessage() {}

func (x *UpdatePayOrderResp) ProtoReflect() protoreflect.Message {
	mi := &file_pay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePayOrderResp.ProtoReflect.Descriptor instead.
func (*UpdatePayOrderResp) Descriptor() ([]byte, []int) {
	return file_pay_proto_rawDescGZIP(), []int{1}
}

func (x *UpdatePayOrderResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UpdatePayOrderResp) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_pay_proto protoreflect.FileDescriptor

var file_pay_proto_rawDesc = []byte{
	0x0a, 0x09, 0x70, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x22, 0xd7, 0x02, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50,
	0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x40, 0x0a, 0x07, 0x50, 0x61,
	0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x26, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x2e, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x45,
	0x6e, 0x75, 0x6d, 0x52, 0x07, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x3c, 0x0a, 0x06,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79,
	0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71, 0x2e, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61,
	0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x50, 0x61, 0x79,
	0x54, 0x69, 0x6d, 0x65, 0x22, 0x5b, 0x0a, 0x0b, 0x50, 0x61, 0x79, 0x54, 0x79, 0x70, 0x65, 0x45,
	0x6e, 0x75, 0x6d, 0x12, 0x05, 0x0a, 0x01, 0x5f, 0x10, 0x00, 0x12, 0x06, 0x0a, 0x02, 0x48, 0x35,
	0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x70, 0x70, 0x6c, 0x65, 0x74, 0x10, 0x02, 0x12, 0x15,
	0x0a, 0x11, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x74, 0x75, 0x64, 0x65, 0x5f, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x10, 0x03, 0x12, 0x0d, 0x0a, 0x09, 0x53, 0x63, 0x61, 0x6e, 0x5f, 0x43, 0x6f,
	0x64, 0x65, 0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x10,
	0x05, 0x22, 0x4b, 0x0a, 0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0f,
	0x0a, 0x0b, 0x57, 0x61, 0x69, 0x74, 0x5f, 0x43, 0x6f, 0x6d, 0x6d, 0x69, 0x74, 0x10, 0x00, 0x12,
	0x0c, 0x0a, 0x08, 0x57, 0x61, 0x69, 0x74, 0x5f, 0x50, 0x61, 0x79, 0x10, 0x01, 0x12, 0x0e, 0x0a,
	0x0a, 0x50, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x4f, 0x75, 0x74, 0x10, 0x02, 0x12, 0x0f, 0x0a,
	0x0b, 0x50, 0x61, 0x79, 0x5f, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x03, 0x22, 0x3a,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4d, 0x73, 0x67, 0x32, 0xa3, 0x01, 0x0a, 0x03, 0x50,
	0x61, 0x79, 0x12, 0x49, 0x0a, 0x0e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x71,
	0x1a, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x12, 0x51, 0x0a,
	0x16, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52,
	0x6f, 0x6c, 0x6c, 0x42, 0x61, 0x63, 0x6b, 0x12, 0x1a, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x61, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pay_proto_rawDescOnce sync.Once
	file_pay_proto_rawDescData = file_pay_proto_rawDesc
)

func file_pay_proto_rawDescGZIP() []byte {
	file_pay_proto_rawDescOnce.Do(func() {
		file_pay_proto_rawDescData = protoimpl.X.CompressGZIP(file_pay_proto_rawDescData)
	})
	return file_pay_proto_rawDescData
}

var file_pay_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pay_proto_goTypes = []interface{}{
	(UpdatePayOrderReq_PayTypeEnum)(0), // 0: service.UpdatePayOrderReq.PayTypeEnum
	(UpdatePayOrderReq_PayStatus)(0),   // 1: service.UpdatePayOrderReq.PayStatus
	(*UpdatePayOrderReq)(nil),          // 2: service.UpdatePayOrderReq
	(*UpdatePayOrderResp)(nil),         // 3: service.UpdatePayOrderResp
}
var file_pay_proto_depIdxs = []int32{
	0, // 0: service.UpdatePayOrderReq.PayType:type_name -> service.UpdatePayOrderReq.PayTypeEnum
	1, // 1: service.UpdatePayOrderReq.Status:type_name -> service.UpdatePayOrderReq.PayStatus
	2, // 2: service.Pay.UpdatePayOrder:input_type -> service.UpdatePayOrderReq
	2, // 3: service.Pay.UpdatePayOrderRollBack:input_type -> service.UpdatePayOrderReq
	3, // 4: service.Pay.UpdatePayOrder:output_type -> service.UpdatePayOrderResp
	3, // 5: service.Pay.UpdatePayOrderRollBack:output_type -> service.UpdatePayOrderResp
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pay_proto_init() }
func file_pay_proto_init() {
	if File_pay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePayOrderReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePayOrderResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pay_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pay_proto_goTypes,
		DependencyIndexes: file_pay_proto_depIdxs,
		EnumInfos:         file_pay_proto_enumTypes,
		MessageInfos:      file_pay_proto_msgTypes,
	}.Build()
	File_pay_proto = out.File
	file_pay_proto_rawDesc = nil
	file_pay_proto_goTypes = nil
	file_pay_proto_depIdxs = nil
}
