// Code generated by goctl. DO NOT EDIT.
package types

type CreatePayReq struct {
	Amount         int    `json:"amount"`
	BizOrderNo     int    `json:"bizOrderNo"`
	OrderInfo      string `json:"orderInfo"`
	PayChannelCode string `json:"payChannelCode"`
	PayType        int    `json:"payType"`
}

type UseBalancePayReq struct {
	Id  int    `path:"id"`
	Uid int64  `json:"id"`
	Pw  string `json:"pw"`
}
