// Code generated by goctl. DO NOT EDIT.
package types

type QueryAddressesResp struct {
	Addresses []QueryAddressesDTO `json:"addresses"`
}

type QueryAddressesDTO struct {
	City      string `json:"city"`
	Contact   string `json:"contact"`
	Id        int    `json:"id"`
	IsDefault int    `json:"isDefault"`
	Mobile    string `json:"mobile"`
	Notes     string `json:"notes"`
	Province  string `json:"province"`
	Street    string `json:"street"`
	Town      string `json:"town"`
}

type FindAddressByIdReq struct {
	AddressId int `path:"addressId"`
}

type FindAddressByIdResp struct {
	QueryAddressesDTO
}
