// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package carts

import (
	"context"

	"hmall/application/cart/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DelCartsReq  = pb.DelCartsReq
	DelCartsResp = pb.DelCartsResp

	Carts interface {
		DelCarts(ctx context.Context, in *DelCartsReq, opts ...grpc.CallOption) (*DelCartsResp, error)
	}

	defaultCarts struct {
		cli zrpc.Client
	}
)

func NewCarts(cli zrpc.Client) Carts {
	return &defaultCarts{
		cli: cli,
	}
}

func (m *defaultCarts) DelCarts(ctx context.Context, in *DelCartsReq, opts ...grpc.CallOption) (*DelCartsResp, error) {
	client := pb.NewCartsClient(m.cli.Conn())
	return client.DelCarts(ctx, in, opts...)
}
