// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"hmall/application/user/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	DecutMoneyReq  = pb.DecutMoneyReq
	DecutMoneyResp = pb.DecutMoneyResp

	User interface {
		DecutMoney(ctx context.Context, in *DecutMoneyReq, opts ...grpc.CallOption) (*DecutMoneyResp, error)
		DecutMoneyRollBack(ctx context.Context, in *DecutMoneyReq, opts ...grpc.CallOption) (*DecutMoneyResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) DecutMoney(ctx context.Context, in *DecutMoneyReq, opts ...grpc.CallOption) (*DecutMoneyResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.DecutMoney(ctx, in, opts...)
}

func (m *defaultUser) DecutMoneyRollBack(ctx context.Context, in *DecutMoneyReq, opts ...grpc.CallOption) (*DecutMoneyResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.DecutMoneyRollBack(ctx, in, opts...)
}
