// Code generated by goctl. DO NOT EDIT.
// Source: cart.proto

package server

import (
	"context"

	"hmall/application/cart/rpc/internal/logic"
	"hmall/application/cart/rpc/internal/svc"
	"hmall/application/cart/rpc/pb"
)

type CartsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCartsServer
}

func NewCartsServer(svcCtx *svc.ServiceContext) *CartsServer {
	return &CartsServer{
		svcCtx: svcCtx,
	}
}

func (s *CartsServer) DelCarts(ctx context.Context, in *pb.DelCartsReq) (*pb.DelCartsResp, error) {
	l := logic.NewDelCartsLogic(ctx, s.svcCtx)
	return l.DelCarts(in)
}

func (s *CartsServer) DelCartsRollBack(ctx context.Context, in *pb.DelCartsReq) (*pb.DelCartsResp, error) {
	l := logic.NewDelCartsRollBackLogic(ctx, s.svcCtx)
	return l.DelCartsRollBack(in)
}
